[build-system]
requires = [
    "Cython<3.0.0",
    "cysignals",
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "gappy/_version.py"
